# Generated by Django 3.2.7 on 2021-09-24 16:20

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(verbose_name=builtins.max),
        ),
    ]
